project:
  type: website

website:
  title: "fantom filters"
  favicon: "favicon.png"
  navbar:
    left:
      - text: blog
        file: index.qmd
      - text: about
        file: about.qmd
      # - icon: github
      #   href: https://github.com/mastoffel
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: brae.scss
    highlight-style: kate

