project:
  type: website
  title: "Malmstrom"

website:
  title: "Malmstrom"
  navbar:
    right:
      - text: "blog"
        file: index.qmd
      - text: "research"
        file: research.qmd
      - text: "about"
        file: about.qmd
      #- icon: github
        #href: https://github.com/mastoffel
      #- icon: twitter
        #href: https://twitter.com
  favicon: favicon_round.png
format:
  html:
    theme: custom.scss
    css: styles.css
    mainfont: "Lato"
    #monofont: "Avenir"
    footnotes-hover: true
    fontsize: 1em
    linkcolor: "black"
highlight-style: kate

editor: visual

