project:
  type: website
  title: "fantom filters"

website:
  title: "fantom filters"
  navbar:
    right:
      - text: "blog"
        file: index.qmd
      - text: "research"
        file: research.qmd
      - text: "about"
        file: about.qmd
      #- icon: github
        #href: https://github.com/mastoffel
      #- icon: twitter
        #href: https://twitter.com
  favicon: favicon.png
  google-analytics: "G-FYLF41PFGT"
format:
  html:
    theme: custom.scss
    css: styles.css
    #mainfont: "Open Sans"
    #monofont: "Avenir"
    footnotes-hover: true
    fontsize: 1em
    linkcolor: "black"
    
highlight-style: kate
callout-appearance: minimal
  
editor: visual

