project:
  type: website
  title: "fantom filters"

website:
  title: "fantom filters"
  site-url: https://www.mstoffel.xyz/
  description: "personal blog"
  search: false
  navbar:
    right:
      - text: "blog"
        file: index.qmd
      - text: "research"
        file: research.qmd
      - text: "code"
        file: code.qmd
      - text: "about"
        file: about.qmd
      # - icon: rss
      #   href: index.xml
  favicon: favicon.png
  google-analytics: "G-FYLF41PFGT"

format:
  html:
    theme: 
     - simplex #custom.scss
     - custom.scss
    #css: styles.css
    #mainfont: "Lato"
    #monofont: "JetBrainsMono"
    footnotes-hover: true
    fontsize: 1em
    linkcolor: "black"
    linestretch: 1.7

  
highlight-style: arrow
callout-appearance: minimal
  
editor: visual

render:
  "!*.ipynb"