project:
  type: website

website:
  title: "Fantom Filters"
  favicon: "favicon.png"
  navbar:
    left:
      - text: Posts
        file: index.qmd
      - text: About
        file: about.qmd
      # - icon: github
      #   href: https://github.com/mastoffel
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: brae.scss
    highlight-style: kate



