project:
  type: website

website:
  title: ""
  favicon: "favicon.png"
  google-analytics: "G-FYLF41PFGT"
  navbar:
    logo: "favicon.png"
    right:
      - text: blog
        file: index.qmd
      - text: about
        file: about.qmd
      # - icon: github
      #   href: https://github.com/mastoffel
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: brae.scss
    highlight-style: kate
    html-math-method: plain
    minimal: false

