project:
  type: website

website:
  title: "fantom filters"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mastoffel
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: brae.scss
    highlight-style: brae.theme



